name: sync_tree_mobile_logic
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pointycastle: ^3.1.1
  basic_utils: ^3.1.0
  clipboard: ^0.1.3
  fixnum: ^1.0.0
  protobuf: ^2.0.0
  grpc: ^3.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
